/*
    Reflexil .NET assembly editor.
    Copyright (C) 2007-2010 Sebastien LEBRETON

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

namespace Reflexil.Compilation
{
    enum EVisualBasicKeyword
    {
        AddHandler,
        AddressOf,
        Alias,
        And,
        AndAlso,
        As,
        Boolean,
        ByRef,
        Byte,
        ByVal,
        Call,
        Case,
        Catch,
        CBool,
        CByte,
        CChar,
        CDate,
        CDec,
        CDbl,
        Char,
        CInt,
        Class,
        CLng,
        CObj,
        Const,
        Continue,
        CSByte,
        CShort,
        CSng,
        CStr,
        CType,
        CUInt,
        CULng,
        CUShort,
        Date,
        Decimal,
        Declare,
        Default,
        Delegate,
        Dim,
        DirectCast,
        Do,
        Double,
        Each,
        Else,
        ElseIf,
        End,
        EndIf,
        Enum,
        Erase,
        Error,
        Event,
        Exit,
        Explicit,
        False,
        Finally,
        For,
        Friend,
        Function,
        Get,
        GetType,
        GetXMLNamespace,
        Global,
        GoSub,
        GoTo,
        Handles,
        If,
        Implements,
        Imports,
        In,
        Inherits,
        Integer,
        Interface,
        Is,
        IsNot,
        Let,
        Lib,
        Like,
        Long,
        Loop,
        Me,
        Mod,
        Module,
        MustInherit,
        MustOverride,
        MyBase,
        MyClass,
        Namespace,
        Narrowing,
        New,
        Next,
        Not,
        Nothing,
        NotInheritable,
        NotOverridable,
        Object,
        Of,
        On,
        Operator,
        Option,
        Optional,
        Or,
        OrElse,
        Overloads,
        Overridable,
        Overrides,
        ParamArray,
        Partial,
        Private,
        Property,
        Protected,
        Public,
        RaiseEvent,
        ReadOnly,
        ReDim,
        REM,
        RemoveHandler,
        Resume,
        Return,
        SByte,
        Select,
        Set,
        Shadows,
        Shared,
        Short,
        Single,
        Static,
        Step,
        Stop,
        Strict,
        String,
        Structure,
        Sub,
        SyncLock,
        Then,
        Throw,
        To,
        True,
        Try,
        TryCast,
        TypeOf,
        Variant,
        Wend,
        UInteger,
        ULong,
        UShort,
        Using,
        When,
        While,
        Widening,
        With,
        WithEvents,
        WriteOnly,
        Xor
    }
}
