//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflexil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase InputBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["InputBase"]));
            }
            set {
                this["InputBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase RowIndexDisplayBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["RowIndexDisplayBase"]));
            }
            set {
                this["RowIndexDisplayBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase OperandDisplayBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["OperandDisplayBase"]));
            }
            set {
                this["OperandDisplayBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharp")]
        public global::Reflexil.Compilation.ESupportedLanguage Language {
            get {
                return ((global::Reflexil.Compilation.ESupportedLanguage)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSymbols {
            get {
                return ((bool)(this["ShowSymbols"]));
            }
            set {
                this["ShowSymbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarning {
            get {
                return ((bool)(this["DisplayWarning"]));
            }
            set {
                this["DisplayWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CacheFiles {
            get {
                return ((bool)(this["CacheFiles"]));
            }
            set {
                this["CacheFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDetectObfuscators {
            get {
                return ((bool)(this["AutoDetectObfuscators"]));
            }
            set {
                this["AutoDetectObfuscators"] = value;
            }
        }
    }
}
