//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.312
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflexil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase InputBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["InputBase"]));
            }
            set {
                this["InputBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase RowIndexDisplayBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["RowIndexDisplayBase"]));
            }
            set {
                this["RowIndexDisplayBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dec")]
        public global::Reflexil.Utils.ENumericBase OperandDisplayBase {
            get {
                return ((global::Reflexil.Utils.ENumericBase)(this["OperandDisplayBase"]));
            }
            set {
                this["OperandDisplayBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharp")]
        public global::Reflexil.Compilation.ESupportedLanguage Language {
            get {
                return ((global::Reflexil.Compilation.ESupportedLanguage)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
    }
}
