using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("1.1.0.176")]
[assembly: AssemblyFileVersionAttribute("1.1.0.176")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0.176")]

